name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync with LeetCode
        uses: fenli/leetcode-sync@master
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: src/main/kotlin
          verbose: true
          commit-header: "[LeetCode Sync]"
